# Generated by Django 5.0.2 on 2024-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='game_id',
        ),
    ]
